// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_UcasHYgqz6A66NwYptDySKNoMoYEnkk',
    appId: '1:1044442052507:web:368a4b49ee8813c07f933e',
    messagingSenderId: '1044442052507',
    projectId: 'planizzer-neyese',
    authDomain: 'planizzer-neyese.firebaseapp.com',
    storageBucket: 'planizzer-neyese.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiFgdpk1iJwFaGyalCjvTesLiejU44_Pg',
    appId: '1:1044442052507:android:88a65bad30b021447f933e',
    messagingSenderId: '1044442052507',
    projectId: 'planizzer-neyese',
    storageBucket: 'planizzer-neyese.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8KJZorAaaojDWLCDn_oWNUWcqCwvlcuM',
    appId: '1:1044442052507:ios:4f2ec1bf4a4e908f7f933e',
    messagingSenderId: '1044442052507',
    projectId: 'planizzer-neyese',
    storageBucket: 'planizzer-neyese.firebasestorage.app',
    iosBundleId: 'com.planizzer.neyese.neyese4',
  );
}
